on:
  pull_request:
    branches:
      - master
      - ash

  push:
    branches:
      - master
      - ash

name: "Build and Release"

jobs:
  build:
    name: "Build and Release"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin" # Use 'zulu' or 'adopt' for different distributions
          java-version: "17" # Latest LTS version as of now

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0" # Ensure this version has Dart SDK >=3.1.2

      - name: Install dependencies
        run: flutter pub get

      - name: Upgrade Dart dependencies
        run: dart pub upgrade

      - name: Check outdated Dart dependencies
        run: dart pub outdated

      - name: Build APK
        run: flutter build apk --debug --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
